### PR TITLE
Implement FAISS GPU support

### PR DESCRIPTION
**Pull request by nictru**
When trying to use the package with FAISS-GPU installed, the GPU was not used automatically and also there was no option for enabling it manually. I added this functionality. 

However, there are some things that would require further discussion:

1. I removed the deep copy of the classifier since the deep copy fails for GPU indices
2. I added an option for disabling the tree printing, since it fails if the GPU is enabled (there is probably an easy fix for this, but I don't know enough about the implementation)

### CODE REVIEW

**Comment by nictru** [comment]
Also it would be nice to have this for the prediction, but I don't yet know how to implement it there

**Comment by lcmmichielsen** [comment]
Hi Nico,

Thanks for your interest in the package! 

- Pandas v2: scHPL unfortunately doesn't work with pandas v2. The update step goes wrong in that case and the same node is added to the tree multiple times. In the first image below, the updating step is correct with pandas v1, in the second image it is wrong with pandas v2. 

- copy.deepcopy(): this can indeed be removed

- printing of the tree: this is quite essential for users. Visualization helps with understanding how cell types are matched. For me using your updated faiss GPU and keeping print_tree=True worked. Could this error at your side have been caused by the pandas update?

- the faiss gpu and compression for training the tree seems to work. Thanks!

So if you fix these things with the pandas requirements and printing of the tree, I think we can merge the pull request.


scHPL_correct
scHPL_wrong

**Comment by nictru** [comment]
Hey, thanks for the feedback! 

- The reason why I changed the pandas version requirement was that I tried to install the package in a larger environment where another tool needed pandas>=2 to work, but I don't do this any more so I will revert this.
- I will check again about the tree printing, maybe I did something wrong. 
- As you can see I added a new commit for GPU usage in prediction. 
- Also I added tqdm since it helped me estimate the duration of the process. I kept it fully optional, but I don't know if you want this to be part of your tool.

**Comment by nictru** [comment]
I think I adressed everything now and all the functionalities I need are there. Apparently I did something wrong with the `print_tree` problem - works like a charm now.

**Comment by nictru** [comment]
The last commit fixas a problem where when a highlighted node name contains an underline `_`, it is interpreted like a LaTeX index command. In some cases the `print_tree` command failed because of this, in other cases it just looked weird. Maybe there is a cleaner way of doing this, but I don't know the syntax that is used there.

**Comment by lcmmichielsen** [comment]
Thanks! Very nice additions with the tqdm and to fix the underscore in the print function!

I tested the code and the GPU works like a charm for me during training, but when trying to use the compress option, the FAISS classifier gives an error and the sklearn kNN is used instead.

About using the GPU during the prediction: what you added now in the predict function is only applied to the classifier trained on the root node instead of to all classifiers in the hierarchy. It might be better to add something to the FaissKNeighbors class itself like you did during training. I was thinking of something like this:

```    
def predict(self, X):
        if self.gpu is not None:
                -> Add classifier.togpu here
        distances, indices = self.index.search(X.astype(np.float32), k=self.k)
        votes = self.y[indices]
        predictions = np.array([np.unique(x)[np.argmax(np.unique(x, return_counts=True)[1])] for x in votes])
        
        return predictions
```

**Comment by nictru** [comment]
For the compression I don't think I know enough about FAISS to make this work properly. I had a problem where the index did not fit into my GPU memory, so I tried this, but the compression took ages. I solved this using subsampling on cell level. I think I will just remove the compress option again.

A problem with the `to_gpu` during prediction is, that it crashes when trying to transfer an index to GPU that is already on the GPU. I will try to find a workaround for this.

**Comment by nictru** [comment]
The problem with `to_gpu` is also that we cannot only do this when `predict` is called, since `parentnode.classifier.kneighbors` is called before (but I think only for the root node).

I tried solving this like this:
```python
# Do PCA if needed
dimred = False
if tree[0].get_dimred():
    pca, pcs = tree[0].get_pca()
    testdata = pca.transform(testdata)
    dimred = True

# Move indices to GPU if needed
if gpu is not None:
    for n in tree[0].walk():
        if n.classifier and n.classifier.__class__ == FaissKNeighbors:
            n.classifier.to_gpu(gpu)

labels_all = []
```

However, this lead to a massive increase of memory usage. I am working on an NVIDIA A40 with 48GB of VRAM, but it basically lead to instand memory allocation error. My theory for this is the following:

1. In the `learn` phase, we removed the `deepcopy`. So potentially the `ìndex` objects could be the same for every node now.
2. When saving as `pickle` the references are resolved and saved as separate instances
3. After loading, we transfer each index separately to the GPU, leading to a multiplication of VRAM usage by the factor of `n_nodes`

Maybe I took a wrong turn here, since I don't know all the rationale between scHPL and FAISS, I wouldn't be too surprised.

**Comment by lcmmichielsen** [comment]
Hmm difficult. I checked the FAISS documentation, but I am not sure either how to fix this efficiently for now. In the beginning it worked sort of automatically, don't know why they changed this.

I suggest we only merge the improvements you made to the print function etc into the master branch now and I will try to fix the GPU at a later point

**Comment by nictru** [comment]
Hey, we can do it like this. I can create a separate PR that cherry-picks only the printing and plotting changes. 

However, for me the `learn` and `predict` functionalities work well as they are here. `predict` also utilizes the GPU properly without crashing, although I don't know how this works as I only send the classifier of the root node to the GPU.

**Review by lcmmichielsen — APPROVED** [review]

**Comment by lcmmichielsen** [comment]
Hi Nico, for me it also works although I am not sure whether it really always using the GPU, but indeed it doesn't crash. So I decided to just approve all changes.

**Pull request merged**
